### ISSUE TITLE
Alternate method of invoking selenium

### ISSUE THREAD

**Issue by phptek** [sveneisenschmidt/selenium-server-standalone#28] opened 2017-07-26 21:46 UTC
In the README is is suggested that args can no longer be passed to selenium-server-standalone. Actually they can ala:

```
java -jar -Dwebdriver.chrome.driver="/vagrant/chromedriver" selenium-server.jar > /dev/null 2>&1 &
```

..just need to re-arrange the order of the args: -D is now passed `before` the jar itself

**Comment by asgrim** [comment] 2017-07-26 22:02
See discussion already had about this in #17. If you have any better suggestions please fire away ;) otherwise, closing this as duplicate of #17

**Closed by asgrim** 2017-07-26 22:02 UTC
