### ISSUE TITLE
Starting Selenium with parameters fails

### ISSUE THREAD

**Issue by andreasschroth** [sveneisenschmidt/selenium-server-standalone#22] opened 2017-02-20 00:56 UTC
Starting Selenium with paramters fails. See the following output:

Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.chrome.driver=/xxx/files/chromedriver
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:219)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)

Solution: PR https://github.com/sveneisenschmidt/selenium-server-standalone/pull/21

**Comment by asgrim** [comment] 2017-02-20 07:18
Duplicate of #17

**Closed** 2017-02-20 07:17 UTC
Labels: duplicate, invalid
